CREATE TABLE `User` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    userId VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL,
    createAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Record (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT,
    opponentId INT NOT NULL,
    isWin BOOL NOT NULL,
    gamedate DATETIME NOT NULL,
    FOREIGN KEY (userId) REFERENCES `User`(id)
);
